version: "3.8"
services: 
  nginx:
    image: nginx:stable
    ports:
      - "80:80"
    environment: 
      NGINX_CONFIG: | 
        server {
          listen 80;
          listen [::]:80;
          gzip on;
          location / {
            proxy_pass http://web:5000;
          }
        }
    command: /bin/sh -c "echo \"$$NGINX_CONFIG\" > /etc/nginx/conf.d/default.conf; nginx -g \"daemon off;\""
  web:
    build:
      context: ../
      dockerfile: compose/Dockerfile
    image: imageprocessor
    ports:
      - "5000:5000"
